# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/distributed-linearmodel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/distributed-linearmodel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/distributed-linearmodel/CMakeFiles /tmp/distributed-linearmodel/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/distributed-linearmodel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named pslite

# Build rule for target.
pslite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pslite
.PHONY : pslite

# fast build rule for target.
pslite/fast:
	$(MAKE) -f ps-lite/CMakeFiles/pslite.dir/build.make ps-lite/CMakeFiles/pslite.dir/build
.PHONY : pslite/fast

#=============================================================================
# Target rules for targets named proto_python

# Build rule for target.
proto_python: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 proto_python
.PHONY : proto_python

# fast build rule for target.
proto_python/fast:
	$(MAKE) -f ps-lite/CMakeFiles/proto_python.dir/build.make ps-lite/CMakeFiles/proto_python.dir/build
.PHONY : proto_python/fast

#=============================================================================
# Target rules for targets named simple_app_test

# Build rule for target.
simple_app_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple_app_test
.PHONY : simple_app_test

# fast build rule for target.
simple_app_test/fast:
	$(MAKE) -f ps-lite/tests/CMakeFiles/simple_app_test.dir/build.make ps-lite/tests/CMakeFiles/simple_app_test.dir/build
.PHONY : simple_app_test/fast

#=============================================================================
# Target rules for targets named connection_test

# Build rule for target.
connection_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 connection_test
.PHONY : connection_test

# fast build rule for target.
connection_test/fast:
	$(MAKE) -f ps-lite/tests/CMakeFiles/connection_test.dir/build.make ps-lite/tests/CMakeFiles/connection_test.dir/build
.PHONY : connection_test/fast

#=============================================================================
# Target rules for targets named kv_app_test

# Build rule for target.
kv_app_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kv_app_test
.PHONY : kv_app_test

# fast build rule for target.
kv_app_test/fast:
	$(MAKE) -f ps-lite/tests/CMakeFiles/kv_app_test.dir/build.make ps-lite/tests/CMakeFiles/kv_app_test.dir/build
.PHONY : kv_app_test/fast

#=============================================================================
# Target rules for targets named kv_app_benchmark_test

# Build rule for target.
kv_app_benchmark_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kv_app_benchmark_test
.PHONY : kv_app_benchmark_test

# fast build rule for target.
kv_app_benchmark_test/fast:
	$(MAKE) -f ps-lite/tests/CMakeFiles/kv_app_benchmark_test.dir/build.make ps-lite/tests/CMakeFiles/kv_app_benchmark_test.dir/build
.PHONY : kv_app_benchmark_test/fast

#=============================================================================
# Target rules for targets named kv_app_multi_workers_test

# Build rule for target.
kv_app_multi_workers_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kv_app_multi_workers_test
.PHONY : kv_app_multi_workers_test

# fast build rule for target.
kv_app_multi_workers_test/fast:
	$(MAKE) -f ps-lite/tests/CMakeFiles/kv_app_multi_workers_test.dir/build.make ps-lite/tests/CMakeFiles/kv_app_multi_workers_test.dir/build
.PHONY : kv_app_multi_workers_test/fast

#=============================================================================
# Target rules for targets named io_test

# Build rule for target.
io_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 io_test
.PHONY : io_test

# fast build rule for target.
io_test/fast:
	$(MAKE) -f tests/CMakeFiles/io_test.dir/build.make tests/CMakeFiles/io_test.dir/build
.PHONY : io_test/fast

#=============================================================================
# Target rules for targets named class_test

# Build rule for target.
class_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 class_test
.PHONY : class_test

# fast build rule for target.
class_test/fast:
	$(MAKE) -f tests/CMakeFiles/class_test.dir/build.make tests/CMakeFiles/class_test.dir/build
.PHONY : class_test/fast

#=============================================================================
# Target rules for targets named metric_test

# Build rule for target.
metric_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 metric_test
.PHONY : metric_test

# fast build rule for target.
metric_test/fast:
	$(MAKE) -f tests/CMakeFiles/metric_test.dir/build.make tests/CMakeFiles/metric_test.dir/build
.PHONY : metric_test/fast

#=============================================================================
# Target rules for targets named config_test

# Build rule for target.
config_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 config_test
.PHONY : config_test

# fast build rule for target.
config_test/fast:
	$(MAKE) -f tests/CMakeFiles/config_test.dir/build.make tests/CMakeFiles/config_test.dir/build
.PHONY : config_test/fast

include/conf/config.pb.o: include/conf/config.pb.cc.o

.PHONY : include/conf/config.pb.o

# target to build an object file
include/conf/config.pb.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/conf/config.pb.cc.o
.PHONY : include/conf/config.pb.cc.o

include/conf/config.pb.i: include/conf/config.pb.cc.i

.PHONY : include/conf/config.pb.i

# target to preprocess a source file
include/conf/config.pb.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/conf/config.pb.cc.i
.PHONY : include/conf/config.pb.cc.i

include/conf/config.pb.s: include/conf/config.pb.cc.s

.PHONY : include/conf/config.pb.s

# target to generate assembly for a file
include/conf/config.pb.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/conf/config.pb.cc.s
.PHONY : include/conf/config.pb.cc.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... edit_cache"
	@echo "... pslite"
	@echo "... proto_python"
	@echo "... simple_app_test"
	@echo "... connection_test"
	@echo "... kv_app_test"
	@echo "... kv_app_benchmark_test"
	@echo "... kv_app_multi_workers_test"
	@echo "... io_test"
	@echo "... class_test"
	@echo "... metric_test"
	@echo "... config_test"
	@echo "... include/conf/config.pb.o"
	@echo "... include/conf/config.pb.i"
	@echo "... include/conf/config.pb.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

